[package]
name = "seven_chain"
version = "0.2.1"
authors = ["daniel <dgw@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
